CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "users_customuser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "users_customuser_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_customuser_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "users_customuser_groups_customuser_id_group_id_76b619e3_uniq" ON "users_customuser_groups" ("customuser_id", "group_id");
CREATE INDEX "users_customuser_groups_customuser_id_958147bf" ON "users_customuser_groups" ("customuser_id");
CREATE INDEX "users_customuser_groups_group_id_01390b14" ON "users_customuser_groups" ("group_id");
CREATE UNIQUE INDEX "users_customuser_user_permissions_customuser_id_permission_id_7a7debf6_uniq" ON "users_customuser_user_permissions" ("customuser_id", "permission_id");
CREATE INDEX "users_customuser_user_permissions_customuser_id_5771478b" ON "users_customuser_user_permissions" ("customuser_id");
CREATE INDEX "users_customuser_user_permissions_permission_id_baaa2f74" ON "users_customuser_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "store_category" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE, "slug" varchar(100) NOT NULL UNIQUE, "hero_video" varchar(100) NULL);
CREATE TABLE IF NOT EXISTS "store_orderitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantity" integer NULL, "date_added" datetime NOT NULL, "order_id" bigint NULL REFERENCES "store_order" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NULL REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED, "product_image" varchar(500) NULL, "product_name" varchar(255) NULL, "product_price" decimal NULL);
CREATE TABLE IF NOT EXISTS "store_shippingadderss" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "address" varchar(200) NOT NULL, "city" varchar(200) NOT NULL, "state" varchar(200) NOT NULL, "zipcode" varchar(200) NOT NULL, "date_added" date NOT NULL, "custamer_id" bigint NULL REFERENCES "store_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "order_id" bigint NULL REFERENCES "store_order" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cart_wishlistitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "added_at" datetime NOT NULL, "product_id" bigint NOT NULL REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED, "wishlist_id" bigint NOT NULL REFERENCES "cart_wishlist" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cart_wishlistitem_product_id_c183b0d4" ON "cart_wishlistitem" ("product_id");
CREATE INDEX "cart_wishlistitem_wishlist_id_dd2c2649" ON "cart_wishlistitem" ("wishlist_id");
CREATE TABLE IF NOT EXISTS "coupons_coupon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(50) NOT NULL UNIQUE, "discount_type" varchar(20) NOT NULL, "value" decimal NOT NULL, "valid_from" datetime NOT NULL, "valid_to" datetime NOT NULL, "active" bool NOT NULL, "max_users" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "coupons_ordercoupon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "discount_amount" decimal NOT NULL, "coupon_id" bigint NULL REFERENCES "coupons_coupon" ("id") DEFERRABLE INITIALLY DEFERRED, "order_id" bigint NOT NULL UNIQUE REFERENCES "store_order" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "coupons_ordercoupon_coupon_id_f53a018d" ON "coupons_ordercoupon" ("coupon_id");
CREATE TABLE IF NOT EXISTS "reviews_review" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "rating" integer NOT NULL, "comment" text NOT NULL, "created_at" datetime NOT NULL, "is_approved" bool NOT NULL, "customer_id" bigint NULL REFERENCES "store_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "reviews_review_customer_id_17e79eab" ON "reviews_review" ("customer_id");
CREATE INDEX "reviews_review_product_id_ce2fa4c6" ON "reviews_review" ("product_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "store_customer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NULL, "email" varchar(200) NOT NULL, "user_id" bigint NULL UNIQUE REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "store_product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(199) NOT NULL, "slug" varchar(199) NOT NULL, "image" varchar(100) NOT NULL, "description" text NOT NULL, "price" decimal NOT NULL, "available" bool NOT NULL, "created" datetime NOT NULL, "updated" datetime NOT NULL, "category_id" bigint NOT NULL REFERENCES "store_category" ("id") DEFERRABLE INITIALLY DEFERRED, "vendor_id" bigint NULL REFERENCES "vendors_vendor" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "store_orderitem_order_id_acf8722d" ON "store_orderitem" ("order_id");
CREATE INDEX "store_product_name_46bbb6a9" ON "store_product" ("name");
CREATE INDEX "store_product_slug_6de8ee4b" ON "store_product" ("slug");
CREATE INDEX "store_product_category_id_574bae65" ON "store_product" ("category_id");
CREATE INDEX "store_product_vendor_id_f9abf9af" ON "store_product" ("vendor_id");
CREATE INDEX "store_orderitem_product_id_f2b098d4" ON "store_orderitem" ("product_id");
CREATE INDEX "store_shippingadderss_custamer_id_321a9222" ON "store_shippingadderss" ("custamer_id");
CREATE INDEX "store_shippingadderss_order_id_17968972" ON "store_shippingadderss" ("order_id");
CREATE TABLE IF NOT EXISTS "transaction_transaction" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "transaction_id" varchar(100) NULL, "amount" decimal NOT NULL, "status" varchar(20) NOT NULL, "payment_method" varchar(50) NOT NULL, "created_at" datetime NOT NULL, "order_id" bigint NOT NULL UNIQUE REFERENCES "store_order" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cart_cart" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "customer_id" bigint NULL REFERENCES "store_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "session_key" varchar(40) NULL);
CREATE INDEX "cart_cart_customer_id_bbe4c408" ON "cart_cart" ("customer_id");
CREATE TABLE IF NOT EXISTS "cart_cartitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantity" bigint unsigned NOT NULL CHECK ("quantity" >= 0), "cart_id" bigint NOT NULL REFERENCES "cart_cart" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED, "price_at_addition" decimal NOT NULL);
CREATE INDEX "cart_cartitem_cart_id_370ad265" ON "cart_cartitem" ("cart_id");
CREATE INDEX "cart_cartitem_product_id_b24e265a" ON "cart_cartitem" ("product_id");
CREATE TABLE IF NOT EXISTS "vendors_vendor" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "slug" varchar(200) NOT NULL UNIQUE, "address" text NOT NULL, "user_id" bigint NOT NULL UNIQUE REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "logo" varchar(100) NULL, "owner_name" varchar(100) NOT NULL, "phone" varchar(20) NOT NULL, "store_name" varchar(200) NOT NULL);
CREATE TABLE IF NOT EXISTS "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" datetime NOT NULL, "user_id" bigint NOT NULL UNIQUE REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "store_contactmessage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "email" varchar(254) NOT NULL, "subject" varchar(200) NOT NULL, "message" text NOT NULL, "created_at" datetime NOT NULL, "is_read" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "store_wishlist" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "added_at" datetime NOT NULL, "product_id" bigint NOT NULL REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "store_wishlist_user_id_product_id_bcc1ac25_uniq" ON "store_wishlist" ("user_id", "product_id");
CREATE INDEX "store_wishlist_product_id_8af1333d" ON "store_wishlist" ("product_id");
CREATE INDEX "store_wishlist_user_id_afcc4e88" ON "store_wishlist" ("user_id");
CREATE TABLE IF NOT EXISTS "store_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_odered" datetime NOT NULL, "complete" bool NOT NULL, "transaction_id" varchar(100) NULL, "custamer_id" bigint NULL REFERENCES "store_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "status" varchar(20) NOT NULL, "carrier" varchar(100) NULL, "delivered_at" datetime NULL, "last_updated" datetime NOT NULL, "shipped_at" datetime NULL, "tracking_number" varchar(100) NULL, "tracking_stage" varchar(32) NOT NULL);
CREATE INDEX "store_order_custamer_id_f612b27d" ON "store_order" ("custamer_id");
CREATE TABLE IF NOT EXISTS "store_productimage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NOT NULL, "alt_text" varchar(255) NULL, "created_at" datetime NOT NULL, "product_id" bigint NOT NULL REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "store_productimage_product_id_e50e4046" ON "store_productimage" ("product_id");
CREATE TABLE IF NOT EXISTS "cart_wishlist" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "created_at" datetime NOT NULL, "customer_id" bigint NOT NULL REFERENCES "store_customer" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cart_wishlist_customer_id_7393ee48" ON "cart_wishlist" ("customer_id");
CREATE TABLE IF NOT EXISTS "store_product_categories" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "product_id" bigint NOT NULL REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED, "category_id" bigint NOT NULL REFERENCES "store_category" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "store_product_categories_product_id_category_id_fe62df28_uniq" ON "store_product_categories" ("product_id", "category_id");
CREATE INDEX "store_product_categories_product_id_de429ba1" ON "store_product_categories" ("product_id");
CREATE INDEX "store_product_categories_category_id_be6ba102" ON "store_product_categories" ("category_id");
