# Generated by Django 5.2.7 on 2025-11-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/categories/'),
        ),
    ]
