# Generated by Django 5.2.7 on 2025-11-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='m2m_products', to='store.category'),
        ),
    ]
