# Generated by Django 5.2.7 on 2025-11-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
