# Generated by Django 5.2.7 on 2025-10-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors_logos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
