"""
Django settings for librashop project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from fcntl import FASYNC
from pathlib import Path
import os
import stripe
from decouple import config

# Optional dependency for DATABASE_URL support
try:
    import dj_database_url
except ImportError:
    dj_database_url = None


# ====== BASE PROJECT PATH ======
BASE_DIR = Path(__file__).resolve().parent.parent


# ====== STRIPE CONFIGURATION ======
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

if STRIPE_SECRET_KEY:
    stripe.api_key = STRIPE_SECRET_KEY



# ====== AUTH / LOGIN SETTINGS ======
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
LOGIN_URL = "login"


# ====== CORE DJANGO SECURITY ======
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-d!5$!wyz!h0lj*_ho!=d=jg1z5z9wcnm5oid=yh#3=sx16&l^(",
)

DEBUG = config("DEBUG", default=False, cast=bool)

# Clean ALLOWED_HOSTS to avoid blank entries
ALLOWED_HOSTS = [
    host.strip() for host in config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",") if host.strip()
]


# ====== INSTALLED APPS ======
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Project apps
    "store",
    "cart",
    "transaction",
    "vendors",
    "reviews",
    "coupons",
    "users",

    # Third-party
    "widget_tweaks",
    "anymail",
    "django.contrib.humanize",
]


# ====== EMAIL (MAILGUN) ======
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
ANYMAIL = {
    "MAILGUN_API_KEY": config("MAILGUN_API_KEY", default=""),
    "MAILGUN_SENDER_DOMAIN": config("MAILGUN_SENDER_DOMAIN", default=""),
}

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="LIBRA Store <noreply@example.com>")
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# ====== CUSTOM USER MODEL ======
AUTH_USER_MODEL = "users.CustomUser"


# ====== MIDDLEWARE ======
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Custom
    "cart.middleware.NoCacheMiddleware",
]


# ====== TEMPLATES ======
ROOT_URLCONF = "librashop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "store.context_processors.cart_wishlist_counts",
            ],
        },
    },
]

WSGI_APPLICATION = "librashop.wsgi.application"


# ====== DATABASE CONFIG ======
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=''),
        conn_max_age=600,
        ssl_require=True
    )
}

# ====== PASSWORD VALIDATORS ======
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]



# ====== INTERNATIONALIZATION ======
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True



# ====== STATIC & MEDIA FILES ======
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# ====== LOGGING ======

# Create logs directory before handler uses it
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "{levelname} {asctime} {module} {message}", "style": "{"},
        "simple": {"format": "{levelname} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "file": {
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "django.log",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": config("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
    },
}



# ====== CSRF / SECURITY SETTINGS ======

# Dev defaults
CSRF_COOKIE_NAME = "csrftoken"
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_USE_SESSIONS = False

# Production overrides
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True



# ====== CUSTOM HOMEPAGE IMAGES ======
HOME_HERO_IMAGES = [
    "images/banners/heroban.png",
    "images/banners/heroban2.png",
    "images/banners/heroban3.png",
]
