# Generated by Django 5.2.7 on 2025-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_session_key_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
