# Generated by Django 5.2.7 on 2025-10-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_price_at_addition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_addition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
