# Generated by Django 5.2.7 on 2025-11-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_price_at_addition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Customer',
            new_name='customer',
        ),
    ]
